import "dotenv/config";
import { chromium, expect, type Page } from "@playwright/test";
import { randomUUID } from "node:crypto";
import assert from "node:assert/strict";
import { mkdir } from "node:fs/promises";
import { eq, inArray } from "drizzle-orm";
import { db, pool } from "../src/db/index.ts";
import { wallets, users, orders, sessions, walletAudit, walletEntries, walletOperations, walletRateLimits } from "../src/db/schema.ts";

const base = process.env.TEST_BASE_URL ?? "http://localhost:3000";
let userId: string | undefined;
let page: Page | undefined;
const browser = await chromium.launch({ headless: true, args: ["--no-sandbox"] });
try {
  await mkdir("artifacts", { recursive: true });
  page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto(base, { waitUntil: "networkidle" });
  await expect(page.getByRole("button", { name: "Демо-режим", exact: true })).toBeVisible();
  await page.screenshot({ path: "artifacts/wallet-desktop.png", fullPage: true });
  await page.locator("#quick-topup-amount").fill("10000");
  await page.locator(".wk-quick-card button[type=submit]").click();
  await expect(page.locator(".modal-surface")).toBeVisible();
  const form = page.locator(".modal-surface form");
  await form.locator("input").nth(0).fill("Wallet Browser QA");
  await form.locator("input[type=email]").fill(`browser-qa-${randomUUID()}@example.com`);
  await form.locator("input[type=password]").fill(`Qa-${randomUUID()}`);
  const registration = page.waitForResponse((r) => r.url().endsWith("/api/auth/register") && r.request().method() === "POST");
  await form.locator("button[type=submit]").click();
  userId = (await (await registration).json()).user.id;
  await expect(page.getByRole("heading", { name: "Пополнить баланс", exact: true })).toBeVisible();
  await page.getByRole("dialog").getByRole("button", { name: "Продолжить", exact: true }).click();
  await expect(page.getByRole("button", { name: "Зачислить тестовые средства" })).toBeVisible();
  await page.screenshot({ path: "artifacts/wallet-topup.png" });
  await page.getByRole("button", { name: "Зачислить тестовые средства" }).click();
  await expect(page.getByRole("heading", { name: "Баланс пополнен", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Перейти к покупкам", exact: true }).click();
  await expect(page.locator(".wk-catalog-product")).toHaveCount(4);
  const card = page.locator(".wk-catalog-product").filter({ has: page.getByRole("heading", { name: "Gemini Pro", exact: true }) });
  await card.getByRole("button", { name: "Купить", exact: false }).click();
  await expect(page.getByRole("heading", { name: "Подтвердите покупку" })).toBeVisible();
  await page.getByLabel("Есть промокод?").fill("LIVKA15");
  await expect(page.getByRole("button", { name: /Подтвердить покупку/ })).toBeEnabled();
  await page.screenshot({ path: "artifacts/wallet-checkout.png" });
  await page.getByRole("button", { name: /Подтвердить покупку/ }).click();
  await expect(page.getByRole("heading", { name: "Доступ уже у вас" })).toBeVisible();
  await page.getByRole("button", { name: "Показать доступ", exact: true }).click();
  await expect(page.locator(".wk-credentials pre")).toContainText("ДЕМОНСТРАЦИОННЫЙ ДОСТУП");
  const downloaded = page.waitForEvent("download");
  await page.getByRole("button", { name: "Сохранить", exact: true }).click();
  assert.match((await downloaded).suggestedFilename(), /^livka-\d+\.txt$/);
  await page.getByRole("dialog").getByRole("button", { name: "Мои покупки", exact: true }).click();
  await expect(page.locator(".wk-purchase-card")).toHaveCount(1);
  await page.reload({ waitUntil: "networkidle" });
  await expect(page.locator(".wk-purchase-card")).toHaveCount(1);
  await page.locator(".wk-sidebar").getByRole("button", { name: /Кошелёк/ }).click();
  await page.getByRole("button", { name: "Вывести", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Вывести средства", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Подставить адрес для тестовой заявки" }).click();
  await page.getByRole("dialog").getByRole("button", { name: "Продолжить", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Подтвердите вывод", exact: true })).toBeVisible();
  await page.getByRole("checkbox").check();
  await page.screenshot({ path: "artifacts/wallet-withdrawal.png" });
  await page.getByRole("button", { name: "Подтвердить вывод", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Заявка создана", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Понятно", exact: true }).click();
  await page.locator(".wk-history-row").filter({ hasText: "Вывод на кошелёк" }).click();
  await page.getByRole("button", { name: "Отменить заявку", exact: true }).click();
  await page.getByRole("button", { name: "Да, отменить", exact: true }).click();
  await expect(page.getByRole("dialog").getByText("Отменено", { exact: true })).toBeVisible();
  await page.keyboard.press("Escape");
  const snapshot = await page.evaluate(async () => (await fetch("/api/wallet")).json());
  assert.equal(snapshot.balanceCents, 575850);
  assert.equal(snapshot.heldCents, 0);
  assert.equal(snapshot.operations.length, 3);
  await page.screenshot({ path: "artifacts/wallet-populated.png", fullPage: true });
  const downloadCsv = page.waitForEvent("download");
  await page.getByRole("button", { name: "Скачать историю в CSV" }).click();
  assert.match((await downloadCsv).suggestedFilename(), /\.csv$/);
  await page.getByRole("tab", { name: "Покупки", exact: true }).click();
  await expect(page.locator(".wk-history-row")).toHaveCount(1);
  await page.getByRole("button", { name: "Скрыть баланс", exact: true }).click();
  await expect(page.locator(".wk-balance-number")).toContainText("••••••");
  await page.getByRole("button", { name: "Показать баланс", exact: true }).click();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth), 1440);
  const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
  mobile.on("pageerror", (error) => errors.push(error.message));
  await mobile.goto(base, { waitUntil: "networkidle" });
  await mobile.screenshot({ path: "artifacts/wallet-mobile.png", fullPage: true });
  assert.equal(await mobile.evaluate(() => document.documentElement.scrollWidth), 390);
  await mobile.getByRole("button", { name: "Открыть меню", exact: true }).click();
  await mobile.getByRole("button", { name: "Каталог", exact: false }).first().click();
  await expect(mobile.getByRole("heading", { name: "Каталог продуктов", exact: true })).toBeVisible();
  await mobile.getByRole("textbox", { name: "Поиск в каталоге" }).fill("ChatGPT");
  await expect(mobile.locator(".wk-catalog-product")).toHaveCount(1);
  assert.equal(errors.length, 0, errors.join("\n"));
  console.log("PASS: browser registration, top-up, discount checkout, credentials download, persisted purchases, withdrawal review, cancellation, CSV export, filtering, hidden balance, responsive layout, mobile navigation, and catalog search. No page errors.");
} catch (error) {
  if (page) await page.screenshot({ path: "artifacts/browser-failure.png", fullPage: true }).catch(() => {});
  throw error;
} finally {
  await browser.close();
  if (userId) {
    const ws = await db.select({ id: wallets.id }).from(wallets).where(eq(wallets.userId, userId));
    if (ws.length) {
      const ids = ws.map((w) => w.id);
      await db.delete(walletEntries).where(inArray(walletEntries.walletId, ids));
      await db.delete(walletAudit).where(inArray(walletAudit.walletId, ids));
      await db.delete(walletOperations).where(inArray(walletOperations.walletId, ids));
      await db.delete(wallets).where(inArray(wallets.id, ids));
    }
    await db.delete(orders).where(eq(orders.userId, userId));
    await db.delete(sessions).where(eq(sessions.userId, userId));
    await db.delete(walletRateLimits).where(inArray(walletRateLimits.key, [`wallet:${userId}`, `withdraw-auth:${userId}`]));
    await db.delete(users).where(eq(users.id, userId));
  }
  await pool.end();
}
